### ISSUE TITLE
Incorrect precedence in LINQ query

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#144]
I have the following C# code:

```csharp
            var numQuery =
                from num in numbers
                select num * 2;
```

This is parsed by tree sitter as:
```csharp
            var numQuery =
                (from num in numbers
                select num) * 2;
```

I expect it to be parsed like this:
```csharp
            var numQuery =
                from num in numbers
                select (num * 2);
```

Here is the tree tree-sitter makes:
```
              (local_declaration_statement [11, 12] - [15, 31]
                (variable_declaration [11, 12] - [15, 30]
                  type: (implicit_type [11, 12] - [11, 15])
                  (variable_declarator [11, 16] - [15, 30]
                    (identifier [11, 16] - [11, 24])
                    (equals_value_clause [11, 25] - [15, 30]
                      (binary_expression [12, 16] - [15, 30]
                        left: (query_expression [12, 16] - [15, 26]
                          (from_clause [12, 16] - [12, 35]
                            (identifier [12, 21] - [12, 24])
                            (identifier [12, 28] - [12, 35]))
                          (comment [13, 16] - [14, 41])
                          (select_clause [15, 16] - [15, 26]
                            (identifier [15, 23] - [15, 26])))
                        right: (integer_literal [15, 29] - [15, 30]))))))
```

**Comment by Sjord** [comment]
@damieng Have you seen this? It the issue clear?

**Comment by damieng** [comment]
I understand this specific issue however the problem is more of one of scope and direction.

The tree-sitter projects have been heavily focused on enabling Semantic support on GitHub.com which was my personal driver for my involvement so far in getting this library to its current state. Many of the other tree-sitter libraries do not offer anywhere near the depth this C# one does and that was only because I found it easier to mirror a lot of the Roslyn C# compiler parsing structures and rules.

This particular bug doesn't not appear to affect any GitHub.com scenarios and I am sure it is just one of a number of bugs that more in-depth analysis and external use might run into and I haven't seen indication that GitHub want to extend tree-sitter libraries much beyond their immediate needs.

As an unpaid community volunteer I have limited time available to spend on this project however could spend a little time reviewing and testing a PR that addressed it if somebody wanted to try and tackle it.

Thanks for your understanding.
