### ISSUE TITLE
Single line comment should end on carriage return

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#170]
Consider a file where the line separator is a single carriage return.

```
class Z {
// comment
}
```

So this is equivalent to

```
class Z {\u000D//comment\u000D}
```

According to the grammar, the carriage return is not a line separator, so the last brace is commented out, resulting in an error:

```
(compilation_unit [0, 0] - [1, 0]
  (class_declaration [0, 0] - [0, 22]
    name: (identifier [0, 6] - [0, 7])
    body: (declaration_list [0, 8] - [0, 22]
      (comment [0, 10] - [0, 22]))))
cr.cs	0 ms	(MISSING "}" [0, 22] - [0, 22])
```

However, roslyn sees the carriage return as a line separator and ends the single-line comment on it. The last brace is not commented.

**Comment by damieng** [comment]
I suspect this one is going to be a limitation upstream in tree-sitter itself as we don't have anything specific about breaking up lines in this grammar.

**Comment by damieng** [comment]
Can you confirm this @maxbrunsfeld ?

**Comment by maxbrunsfeld** [comment]
In general, Tree-sitter does not consider a single carriage return to be a line separator. This is baked into the library; it's designed to match other source-code processing tools like `grep`, `vim`, `git`, etc.

So for files with this line separator, Tree-sitter's row/column information may not match the user's intent. However we're still perfectly able to *parse* the comments however we want: that's up to the grammar. So we could change the definition of `comment` so that it stops on a carriage return.
