### ISSUE TITLE
Allow reserved identifiers as names in named arguments.

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#73]
These were introduced in C# 4, looking like so:

```csharp
resultNode = SimplificationHelpers.CopyAnnotations(from: node, to: resultNode);
```

**Comment by damieng** [comment]
I can jump on this one right now if nobody is working on it.

**Comment by patrickt** [comment]
@damieng Please! Much appreciated. I’m currently going through and analyzing parse errors we find on `dotnet/roslyn`, so feel free to jump on any one of these issues I’m filing.

**Comment by damieng** [comment]
Great! Not sure how I missed the named arguments but I suspect out and ref are also missing on the calling side (but are done on the function definition side).

**Comment by maxbrunsfeld** [comment]
Awesome! Also @damieng, feel free to close multiple issues in one PR if it is easier.

**Comment by damieng** [comment]
So we do actually support named parameters although we don't have decent corpus coverage. The problem on this line isn't actually the lack of named parameter support it's the presence of the words "from" which is a contextually-reserved word in C# used by the LINQ comprehension syntax such as `select a from b into c`. 

I'll investigate what we can do about that.

**Comment by maxbrunsfeld** [comment]
Yeah, it looks in that same position (function arguments) `from` is valid as a keyword (because a `query_expression` can begin with `from`). It looks like this has already been handled in other places via this `reserved_identifier` rule:

https://github.com/tree-sitter/tree-sitter-c-sharp/blob/bb0c2839c48555391fb58be71a52b0dca45537d8/grammar.js#L1415-L1418

I think we just need to allow `_reserved_identifier` inside a `name_colon` node (which models the `from:` bit in this example), similarly to how its included in `_expression` (aliased as a normal `identifier`):

https://github.com/tree-sitter/tree-sitter-c-sharp/blob/bb0c2839c48555391fb58be71a52b0dca45537d8/grammar.js#L1266

**Comment by patrickt** [comment]
Aha, that was the issue—changed the title to reflect this. Thanks, @damieng!
